services:
  - type: web
    name: buddy-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /admin/health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /data
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false


