services:
  - type: web
    name: secret-buddy-dhr
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATA_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
